### ISSUE TITLE
Upgrade to appium 2.0

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/graybox#8]
Appium wouldn’t recognise installed packges in graybox package. Checked on fresh node project with both yarn and npm and it detects that the package is installed, but on graybox it doesn’t. Bottom log is fresh node project, Top log is graybox package. Docs about this (DIY with npm bit) https://appium.io/docs/en/2.0/guides/managing-exts/
<img width="703" alt="Screenshot 2023-06-27 at 09 33 20" src="https://github.com/flexn-io/graybox/assets/65670660/85b40fe3-4a49-44fe-8fce-1fcbe778cf87">

How to test:
1. Graybox env where doesn't work: checkout `chore/upgrade-to-appium2`, do `yarn bootstrap-clean`, go to packages/graybox, do `npx appium` -> logs say that no drivers found
2. Fresh node project where works: `do npm init -y`, add following bit
```
  "devDependencies": {
    "appium": "2.0.0-rc.3",
    "appium-xcuitest-driver": "4.32.9"
  }
```
do `yarn`, do `npx appium` -> logs say that there is 1 driver found

**Comment by mihaiblaga89** [comment]
@pauliusguzas this seems like a non-issue. Looking at their docs, https://github.com/appium/appium-xcuitest-driver, by the looks of it you can't just install the driver into your dependency and expect it to work, it's not even looking in node_modules. `No drivers have been installed in /Users/lego/.appium.` As soon as I ran `yarn appium driver install xcuitest`  
```
 yarn appium driver install xcuitest
yarn run v1.22.19
$ /Users/lego/work/graybox/node_modules/.bin/appium driver install xcuitest
✔ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver'
ℹ Driver xcuitest@4.32.11 successfully installed
- automationName: XCUITest
- platformNames: ["iOS","tvOS"]
✨  Done in 42.72s.
```
it installed it in `[debug] [Appium] Requiring driver at /Users/lego/.appium/node_modules/appium-xcuitest-driver` using NPM and that was it, it started working.

```
❯ yarn appium
yarn run v1.22.19
$ /Users/lego/work/graybox/node_modules/.bin/appium
[Appium] Welcome to Appium v2.0.0 (REV 4f7bcaa7783eac793ca65a382e9b123ddfb4c035)
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at /Users/lego/.appium/node_modules/appium-xcuitest-driver
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLS in your client code to connect to this server:
[Appium] 	http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] 	http://192.168.68.58:4723/
[Appium] 	http://10.242.179.251:4723/
[Appium] Available drivers:
[Appium]   - xcuitest@4.32.11 (automationName 'XCUITest')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
```

**Comment by pauliusguzas** [comment]
@mihaiblaga89 no, there are 2 ways you can install drivers in appium 2.0, check this https://appium.io/docs/en/2.0/guides/managing-exts/ and it does work with adding xcuitest driver to dependencies in package.json when testing in created from scratch node project, but in graybox it doesn't work

**Comment by mihaiblaga89** [comment]
@pauliusguzas you're right, I missed that part in the docs. For some reason in our setup it fails to register it's an npm package, maybe because of monorepo. Pushed a fix with a workaround, just run bootstrap-clean and yarn appium in packages/graybox

**Comment by mihaiblaga89** [comment]
@pauliusguzas any updates on this?

**Comment by pauliusguzas** [comment]
@mihaiblaga89 not much, just started looking today

**Comment by pauliusguzas** [comment]
tried this solution on create and facing issues, driver is not found, branch is here https://github.com/flexn-io/create/tree/chore/appium-2-integration

**Comment by mihaiblaga89** [comment]
@pauliusguzas if you add appium and driver to devDep in the template it works
```
"appium": "2.0.0",
"appium-xcuitest-driver": "4.32.11",
```



![Image](https://github.com/flexn-io/graybox/assets/4787898/2001f4d8-f54d-458f-b238-989271910e92)

**Comment by pauliusguzas** [comment]
@mihaiblaga89 but that should be avoided as graybox has these deps

**Comment by mihaiblaga89** [comment]
I know, but it seems that appium doesn't like that

**Comment by mihaiblaga89** [comment]
I'll look for ways to avoid this

**Comment by mihaiblaga89** [comment]
@pauliusguzas pushed fix to branch, don't forget to run bootstrap-clean


![Image](https://github.com/flexn-io/graybox/assets/4787898/1d65fd53-b1c1-4bca-b6f3-77cf39f44fef)

**Comment by pauliusguzas** [comment]
@mihaiblaga89 is this bit supposed to be added to every monorepo when adding graybox or just ours?
<img width="200" alt="Screenshot 2023-08-23 at 10 09 59" src="https://github.com/flexn-io/graybox/assets/65670660/1b5e5f44-4c51-4146-bfda-f6e80542db08">

**Comment by mihaiblaga89** [comment]
every monorepo. Otherwise appium doesn't work. But just monorepos, classic projects should work just fine
